SELECT Emp.*, Usr.*, Addr.*, EmpProd.*, Prod.*, Ver.*, ProdArea.*, Area.*, ProdCat.*, Cat.*, Ctm.*, Cit.*, Cntr.*, EmpRol.*, Rol.*, Comp.*
FROM Employees Emp JOIN Users Usr ON (Emp.User = Usr.idUser) 
	 JOIN Addresses Addr ON(Emp.Address = Addr.idAddress)
     JOIN Emplpyees Emp ON (Emp.idEmployee = Emp.ReportsTO) 
	 JOIN Employee_Products EmpProd ON(Emp.idEmployee = EmpProd.Product)
     JOIN Products Prod ON(Prod.idProduct = EmpProd.Employee)
	 JOIN Version Ver ON(Prod.idProduct = Ver.Product) 
     JOIN Products_Areas ProdArea ON (Prod.idProduct = ProdArea.Product)
     JOIN Areas Area ON (Area.idArea= ProdArea.Area)
     JOIN Products_Categories ProdCat ON(Prod.idProduct = ProdCat.Product)
     JOIN Categories Cat ON (Cat.idCategory = ProdCat.Category)
     JOIN Costumers Ctm ON (Ctm.Address = Addr.idAddress)
     JOIN Cities Cit ON (Addr.City = Cit.idCity)
     JOIN Countries Cntr ON (Cntr.idCountry = Cit.Country)
     JOIN Employees_Roles EmpRol ON (Emp.idEmployee = EmpRol.Employee)
     JOIN Roles Rol ON (EmpRol.Rol = Rol.idRol)
     JOIN Company Comp ON (Comp.Address = Addr.idAddress)