-- MySQL Script generated by MySQL Workbench
-- Tue Jul 20 16:33:48 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `UserName` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUsers_UNIQUE` (`idUser` ASC) VISIBLE,
  UNIQUE INDEX `UserName_UNIQUE` (`UserName` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Countries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Countries` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Countries` (
  `idCountry` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `AreaCode` INT NOT NULL,
  PRIMARY KEY (`idCountry`),
  UNIQUE INDEX `idCountry_UNIQUE` (`idCountry` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cities` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cities` (
  `idCity` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `ZipCode` DOUBLE NOT NULL,
  `Country` INT NOT NULL,
  PRIMARY KEY (`idCity`),
  UNIQUE INDEX `idCities_UNIQUE` (`idCity` ASC) VISIBLE,
  INDEX `fk_Cities_Country1_idx` (`Country` ASC) VISIBLE,
  CONSTRAINT `fk_Cities_Country1`
    FOREIGN KEY (`Country`)
    REFERENCES `mydb`.`Countries` (`idCountry`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Addresses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Addresses` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Addresses` (
  `idAddress` INT NOT NULL AUTO_INCREMENT,
  `Street` VARCHAR(45) NOT NULL,
  `Number` INT NOT NULL,
  `City` INT NOT NULL,
  PRIMARY KEY (`idAddress`),
  INDEX `fk_Addresses_Cities1_idx` (`City` ASC) VISIBLE,
  UNIQUE INDEX `idAddresses_UNIQUE` (`idAddress` ASC) VISIBLE,
  CONSTRAINT `fk_Addresses_Cities1`
    FOREIGN KEY (`City`)
    REFERENCES `mydb`.`Cities` (`idCity`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Employees` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Employees` (
  `idEmployee` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `BirthDate` DATE NOT NULL,
  `HireDate` DATE NOT NULL,
  `Phone` DOUBLE NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Address` INT NOT NULL,
  `User` INT NOT NULL,
  `ReportsTo` INT NULL,
  PRIMARY KEY (`idEmployee`),
  UNIQUE INDEX `idEmployee_UNIQUE` (`idEmployee` ASC) VISIBLE,
  INDEX `fk_Employee_Addresses1_idx` (`Address` ASC) VISIBLE,
  INDEX `fk_Employee_Users1_idx` (`User` ASC) VISIBLE,
  INDEX `fk_Employee_Employee1_idx` (`ReportsTo` ASC) VISIBLE,
  CONSTRAINT `fk_Employee_Addresses1`
    FOREIGN KEY (`Address`)
    REFERENCES `mydb`.`Addresses` (`idAddress`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_Employee_Users1`
    FOREIGN KEY (`User`)
    REFERENCES `mydb`.`Users` (`idUser`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Employee_Employee1`
    FOREIGN KEY (`ReportsTo`)
    REFERENCES `mydb`.`Employees` (`idEmployee`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Roles` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Roles` (
  `idRol` INT NOT NULL AUTO_INCREMENT,
  `RolName` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(45) NULL,
  PRIMARY KEY (`idRol`),
  UNIQUE INDEX `idRol_UNIQUE` (`idRol` ASC) VISIBLE,
  UNIQUE INDEX `RolName_UNIQUE` (`RolName` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Products` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Products` (
  `idProducts` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProducts`),
  UNIQUE INDEX `idProducts_UNIQUE` (`idProducts` ASC) VISIBLE,
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Categories` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Categories` (
  `idCategories` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(45) NULL,
  PRIMARY KEY (`idCategories`),
  UNIQUE INDEX `idCategories_UNIQUE` (`idCategories` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Products-Categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Products-Categories` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Products-Categories` (
  `Products_idProducts` INT NOT NULL,
  `Categories_idCategories` INT NOT NULL,
  `ProductsXCategoriescol` INT NOT NULL AUTO_INCREMENT,
  INDEX `fk_Products_has_Categories_Categories1_idx` (`Categories_idCategories` ASC) VISIBLE,
  INDEX `fk_Products_has_Categories_Products_idx` (`Products_idProducts` ASC) VISIBLE,
  PRIMARY KEY (`ProductsXCategoriescol`),
  UNIQUE INDEX `ProductsXCategoriescol_UNIQUE` (`ProductsXCategoriescol` ASC) VISIBLE,
  CONSTRAINT `fk_Products_has_Categories_Products`
    FOREIGN KEY (`Products_idProducts`)
    REFERENCES `mydb`.`Products` (`idProducts`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Products_has_Categories_Categories1`
    FOREIGN KEY (`Categories_idCategories`)
    REFERENCES `mydb`.`Categories` (`idCategories`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Versions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Versions` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Versions` (
  `idVersion` INT NOT NULL AUTO_INCREMENT,
  `ReleaseDate` DATE NOT NULL,
  `Description` VARCHAR(45) NULL,
  `Products_idProducts` INT NOT NULL,
  PRIMARY KEY (`idVersion`, `Products_idProducts`),
  UNIQUE INDEX `idVersion_UNIQUE` (`idVersion` ASC) VISIBLE,
  INDEX `fk_Version_Products1_idx` (`Products_idProducts` ASC) VISIBLE,
  CONSTRAINT `fk_Version_Products1`
    FOREIGN KEY (`Products_idProducts`)
    REFERENCES `mydb`.`Products` (`idProducts`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee-Products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Employee-Products` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Employee-Products` (
  `Products_idProducts` INT NOT NULL,
  `Employee_idEmployee` INT NOT NULL,
  `ProductsXEmployeecol` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  INDEX `fk_Products_has_Employee_Employee1_idx` (`Employee_idEmployee` ASC) VISIBLE,
  INDEX `fk_Products_has_Employee_Products1_idx` (`Products_idProducts` ASC) VISIBLE,
  PRIMARY KEY (`ProductsXEmployeecol`),
  CONSTRAINT `fk_Products_has_Employee_Products1`
    FOREIGN KEY (`Products_idProducts`)
    REFERENCES `mydb`.`Products` (`idProducts`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Products_has_Employee_Employee1`
    FOREIGN KEY (`Employee_idEmployee`)
    REFERENCES `mydb`.`Employees` (`idEmployee`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Costumers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Costumers` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Costumers` (
  `idCostumer` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Phone` DOUBLE NULL,
  `Address` INT NOT NULL,
  PRIMARY KEY (`idCostumer`),
  UNIQUE INDEX `idCostumers_UNIQUE` (`idCostumer` ASC) VISIBLE,
  INDEX `fk_Costumers_Addresses1_idx` (`Address` ASC) VISIBLE,
  CONSTRAINT `fk_Costumers_Addresses1`
    FOREIGN KEY (`Address`)
    REFERENCES `mydb`.`Addresses` (`idAddress`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Company` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Company` (
  `idCompany` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `UBK` DOUBLE NOT NULL,
  `WebPage` VARCHAR(45) NOT NULL,
  `Phone` DOUBLE NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Address` INT NOT NULL,
  PRIMARY KEY (`idCompany`),
  UNIQUE INDEX `idCompany_UNIQUE` (`idCompany` ASC) VISIBLE,
  INDEX `fk_Company_Addresses1_idx` (`Address` ASC) VISIBLE,
  CONSTRAINT `fk_Company_Addresses1`
    FOREIGN KEY (`Address`)
    REFERENCES `mydb`.`Addresses` (`idAddress`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Areas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Areas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Areas` (
  `idAreas` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAreas`),
  UNIQUE INDEX `idAreas_UNIQUE` (`idAreas` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Products-Areas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Products-Areas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Products-Areas` (
  `Areas_idAreas` INT NOT NULL,
  `Products_idProducts` INT NOT NULL,
  `AreasXProductscol` INT NOT NULL AUTO_INCREMENT,
  INDEX `fk_Areas_has_Products_Products1_idx` (`Products_idProducts` ASC) VISIBLE,
  INDEX `fk_Areas_has_Products_Areas1_idx` (`Areas_idAreas` ASC) VISIBLE,
  PRIMARY KEY (`AreasXProductscol`),
  UNIQUE INDEX `AreasXProductscol_UNIQUE` (`AreasXProductscol` ASC) VISIBLE,
  CONSTRAINT `fk_Areas_has_Products_Areas1`
    FOREIGN KEY (`Areas_idAreas`)
    REFERENCES `mydb`.`Areas` (`idAreas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Areas_has_Products_Products1`
    FOREIGN KEY (`Products_idProducts`)
    REFERENCES `mydb`.`Products` (`idProducts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employees-Roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Employees-Roles` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Employees-Roles` (
  `Employee` INT NOT NULL,
  `Rol` INT NOT NULL,
  `EmployeeRoles` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`EmployeeRoles`),
  INDEX `fk_Employee_has_Rol_Rol1_idx` (`Rol` ASC) VISIBLE,
  INDEX `fk_Employee_has_Rol_Employee1_idx` (`Employee` ASC) VISIBLE,
  CONSTRAINT `fk_Employee_has_Rol_Employee1`
    FOREIGN KEY (`Employee`)
    REFERENCES `mydb`.`Employees` (`idEmployee`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Employee_has_Rol_Rol1`
    FOREIGN KEY (`Rol`)
    REFERENCES `mydb`.`Roles` (`idRol`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
